# Generated by Django 5.1.6 on 2025-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
